spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api
    username: root
    password: Dragon5*

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: false   # ✅ ADD THIS LINE

server:
  port: 9091