spring:
  application:
    name: store

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}